version: '3.8'

services:
  api:
    container_name: api
    image: eternalrival/home-library-service:api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
    environment:
      PGHOST: db
    networks:
      - hls
  db:
    container_name: db
    image: eternalrival/home-library-service:db
    restart: unless-stopped
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - '${PGPORT}:${PGPORT}'
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_HOST: ${PGHOST}
      POSTGRES_PORT: ${PGPORT}
    networks:
      - hls

networks:
  hls:

volumes:
  db-data:
  db-logs:
